
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx-2
  labels:
    app: my-nginx-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-nginx-2
  template:
    metadata:
      labels:
        app: my-nginx-2
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80