apiVersion: v1
kind: Pod
metadata:
  name: web-nginx
  labels:
    app: nginx
    rel: stable
spec:
  containers:
    - name: web-nginx
      image: nginx
      ports:
        - name: web-nginx
          containerPort: 80
          protocol: TCP
      livenessProbe:
          httpGet:
              path: /index.html
              port: 80
          initialDelaySeconds: 15
          timeoutSeconds: 2
          periodSeconds: 5
          failureThreshold: 1
      readinessProbe:
          tcpSocket:
              port: 80
          initialDelaySeconds: 3
          periodSeconds: 5
          failureThreshold: 1





          #cd /usr/share/nginx/html
          #rm -rf index.html 
