
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx-1
  labels:
    app: my-nginx-1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-nginx-1
  template:
    metadata:
      labels:
        app: my-nginx-1
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80